import { StyleSheet } from 'react-native'


export const estilos = (tema) => {

    return StyleSheet.create({
        container: {
            flex: 1,
            alignItems: 'center',
            backgroundColor: tema.fundo,
        },
        tituloArea: {
            width: '100%',
            height: 65,
            alignItems: 'center',
            justifyContent: 'space-around',
            flexDirection: 'row',
            marginBottom: 16,
            marginTop: 55,
        },
        pedidoArea: {
            flexDirection: 'row',
            alignItems: 'flex-end',
            justifyContent: 'flex-end',
            marginLeft: '-28%',
        },
        pedidoComandaArea: {
            flexDirection: 'row',
            alignItems: 'flex-end',
            justifyContent: 'flex-end',
            marginLeft: '-28%',
        },
        mesaArea: {
            width: '28%',
            alignItems: 'center',
            justifyContent: 'center',
            borderRadius: 10,
            margin: 5,
            padding: 5,
            backgroundColor: tema.fundoBotao,
            borderRadius: 10,
            shadowColor: tema.borda,
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.35,
            shadowRadius: 3.84,
            elevation: 5,
        },
        comanda2Area: {
            width: '42%',
            alignItems: 'center',
            justifyContent: 'center',
            borderRadius: 10,
            margin: 5,
            padding: 5,
            backgroundColor: tema.fundoBotao,
            borderRadius: 10,
            shadowColor: tema.borda,
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.25,
            shadowRadius: 3.84,
            elevation: 5,
        },
        comandaArea: {
            width: '28%',
            alignItems: 'center',
            justifyContent: 'center',
            borderRadius: 10,
            margin: 5,
            padding: 5,
            backgroundColor: tema.fundoBotao,
            borderRadius: 10,
            shadowColor: tema.borda,
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.25,
            shadowRadius: 3.84,
            elevation: 5,
        },
        texto: {
            fontSize: 12,
            fontWeight: 'bold',
            color: tema.tema,
            top: 2,
        },
        numero: {
            fontSize: 18,
            fontWeight: 'bold',
            color: tema.tema,
            marginBottom: 2,
        },
        botaoArea: {
            flexDirection: 'row',
            alignItems: 'flex-end',
            justifyContent: 'flex-end',
            marginLeft: '-18%',
        },
        carrinhoQuantidade: {
            fontSize: 12,
            fontWeight: 'bold',
            color: '#fff',
        },
        botaoCarrinho: {
            flexDirection: 'row',
            borderColor: '#FFF',
            borderRadius: 8,
            margin: 5,
            padding: 10,
            backgroundColor: tema.fundoBotao,
            borderRadius: 10,
            shadowColor: tema.borda,
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.35,
            shadowRadius: 3.84,
            elevation: 5,
        },
        botaoConta: {
            width: '30%',
            flexDirection: 'row',
            borderColor: '#FFF',
            alignItems: 'center',
            justifyContent: 'center',
            borderRadius: 8,
            margin: 5,
            padding: 10,
            backgroundColor: tema.fundoBotao,
            borderRadius: 10,
            shadowColor: tema.borda,
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.35,
            shadowRadius: 3.84,
            elevation: 5,
        },
        carrinhoIcon: {
            fontSize: 32,
            color: tema.tema,
        },
        carrinhoQuantidadeArea: {
            backgroundColor: 'red',
            borderRadius: 10,
            width: 20,
            height: 20,
            alignItems: 'center',
            justifyContent: 'center',
        },
        contaIcon: {
            color: tema.tema,
            fontSize: 32,
        },
        input: {
            height: 45,
            width: '73%',
            backgroundColor: '#F1F2F3',
            marginBottom: 15,
            padding: 10,
            borderRadius: 5,
            color: '#000000',
            fontSize: 18,
        },
        pequisarArea: {
            flexDirection: 'row',
            justifyContent: 'center',
            marginTop: -6,
            marginLeft: 2,

        },
        botao: {
            height: 45,
            width: '16%',
            backgroundColor: tema.tema,
            borderRadius: 8,
            alignItems: 'center',
            justifyContent: 'center',
            marginLeft: 10
        },
        imageTopo: {
            height: 42,
            width: 90,
            alignItems: 'center',
            marginEnd: '-8%'

        },
        topoArea: {
            width: '100%',
            alignItems: 'center',
            flexDirection: 'row',
            backgroundColor: "#CBA122",
            justifyContent: 'space-around',
            position: "absolute",
            top: 0,
        },
        textoTopo: {
            fontSize: 18,
            fontWeight: 'bold',
            color: tema.texto,
            alignItems: 'center',
        },
        menu: {
            padding: 10,
            marginLeft: '-10%',
            flexDirection: 'row',
            alignItems: 'center',
        },
        lista: {
            flex: 1,
            width: '100%',
        },
    })
}